version: '3.8'
services:
  scanner:
    image: pooling-be:latest
    labels:
      - "com.docker.compose.project=pooling-be"
    build:
      context: ./
      cache_from:
        - node:lts-alpine
      dockerfile:  ./Dockerfile
    env_file: .env
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - './logs:/app/logs'
