-- Create a table called countries
INSERT INTO countries (name, id) VALUES ('China', 1);
INSERT INTO countries (name, id) VALUES ('England', 2);
INSERT INTO countries (name, id) VALUES ('United States', 3);

-- Create a table called states
INSERT INTO states (name, id, country_id) VALUES ('Shanghai', 1, 1);
INSERT INTO states (name, id, country_id) VALUES ('Beijing', 2, 1);
INSERT INTO states (name, id, country_id) VALUES ('Tianjin', 3, 1);
INSERT INTO states (name, id, country_id) VALUES ('Guangdong', 4, 1);
INSERT INTO states (name, id, country_id) VALUES ('Jiangsu', 5, 1);
INSERT INTO states (name, id, country_id) VALUES ('Shandong', 6, 1);
INSERT INTO states (name, id, country_id) VALUES ('Hebei', 7, 1);
INSERT INTO states (name, id, country_id) VALUES ('Zhejiang', 8, 1);
INSERT INTO states (name, id, country_id) VALUES ('Sichuan', 9, 1);
INSERT INTO states (name, id, country_id) VALUES ('Hunan', 10, 1);
INSERT INTO states (name, id, country_id) VALUES ('Anhui', 11, 1);
INSERT INTO states (name, id, country_id) VALUES ('Hubei', 12, 1);
INSERT INTO states (name, id, country_id) VALUES ('Henan', 13, 1);
INSERT INTO states (name, id, country_id) VALUES ('Guangxi', 14, 1);
INSERT INTO states (name, id, country_id) VALUES ('Jiangxi', 15, 1);
INSERT INTO states (name, id, country_id) VALUES ('Liaoning', 16, 1);
INSERT INTO states (name, id, country_id) VALUES ('Fujian', 17, 1);
INSERT INTO states (name, id, country_id) VALUES ('Shaanxi', 18, 1);
INSERT INTO states (name, id, country_id) VALUES ('Yunnan', 19, 1);
INSERT INTO states (name, id, country_id) VALUES ('Hainan', 20, 1);
INSERT INTO states (name, id, country_id) VALUES ('London', 21, 2);
INSERT INTO states (name, id, country_id) VALUES ('Birmingham', 22, 2);
INSERT INTO states (name, id, country_id) VALUES ('Leeds', 23, 2);
INSERT INTO states (name, id, country_id) VALUES ('Glasgow', 24, 2);
INSERT INTO states (name, id, country_id) VALUES ('Sheffield', 25, 2);
INSERT INTO states (name, id, country_id) VALUES ('Bradford', 26, 2);
INSERT INTO states (name, id, country_id) VALUES ('Liverpool', 27, 2);
INSERT INTO states (name, id, country_id) VALUES ('Edinburgh', 28, 2);
INSERT INTO states (name, id, country_id) VALUES ('Manchester', 29, 2);
INSERT INTO states (name, id, country_id) VALUES ('Bristol', 30, 2);
INSERT INTO states (name, id, country_id) VALUES ('California', 31, 3);
INSERT INTO states (name, id, country_id) VALUES ('Texas', 32, 3);
INSERT INTO states (name, id, country_id) VALUES ('Florida', 33, 3);
INSERT INTO states (name, id, country_id) VALUES ('New York', 34, 3);
INSERT INTO states (name, id, country_id) VALUES ('Illinois', 35, 3);
INSERT INTO states (name, id, country_id) VALUES ('Pennsylvania', 36, 3);
INSERT INTO states (name, id, country_id) VALUES ('Ohio', 37, 3);
INSERT INTO states (name, id, country_id) VALUES ('Georgia', 38, 3);
INSERT INTO states (name, id, country_id) VALUES ('North Carolina', 39, 3);
INSERT INTO states (name, id, country_id) VALUES ('Michigan', 40, 3);
INSERT INTO states (name, id, country_id) VALUES ('New Jersey', 41, 3);
INSERT INTO states (name, id, country_id) VALUES ('Virginia', 42, 3);
INSERT INTO states (name, id, country_id) VALUES ('Washington', 43, 3);
INSERT INTO states (name, id, country_id) VALUES ('Arizona', 44, 3);
INSERT INTO states (name, id, country_id) VALUES ('Massachusetts', 45, 3);
INSERT INTO states (name, id, country_id) VALUES ('Tennessee', 46, 3);
INSERT INTO states (name, id, country_id) VALUES ('Indiana', 47, 3);
INSERT INTO states (name, id, country_id) VALUES ('Missouri', 48, 3);
INSERT INTO states (name, id, country_id) VALUES ('Maryland', 49, 3);
INSERT INTO states (name, id, country_id) VALUES ('Wisconsin', 50, 3);

-- Create a table called sections
INSERT INTO sections (name, id) VALUES ('Agriculture, forestry & fishing*', 1);
INSERT INTO sections (name, id) VALUES ('Mining & quarrying', 2);
INSERT INTO sections (name, id) VALUES ('Manufacturing', 3);
INSERT INTO sections (name, id) VALUES ('Electricity, gas, steam & air conditioning supply', 4);
INSERT INTO sections (name, id) VALUES ('Water supply; sewerage, waste management & remediation activities', 5);
INSERT INTO sections (name, id) VALUES ('Construction', 6);
INSERT INTO sections (name, id) VALUES ('Wholesale & retail trade; repair of motor vehicles & motorcycles', 7);
INSERT INTO sections (name, id) VALUES ('Transportation & storage', 8);
INSERT INTO sections (name, id) VALUES ('Accommodation & food service activities', 9);
INSERT INTO sections (name, id) VALUES ('Information & communication', 10);
INSERT INTO sections (name, id) VALUES ('Financial & insurance activities', 11);
INSERT INTO sections (name, id) VALUES ('Real estate activities', 12);
INSERT INTO sections (name, id) VALUES ('Professional, scientific & technical activities', 13);
INSERT INTO sections (name, id) VALUES ('Administrative & support service activities', 14);
INSERT INTO sections (name, id) VALUES ('Public administration & defence; compulsory social security', 15);
INSERT INTO sections (name, id) VALUES ('Education', 16);
INSERT INTO sections (name, id) VALUES ('Human health & social work activities', 17);
INSERT INTO sections (name, id) VALUES ('Arts, entertainment & recreation', 18);
INSERT INTO sections (name, id) VALUES ('Other service activities', 19);
INSERT INTO sections (name, id) VALUES ('Activities of households as employers; undifferentiated goods- & services-producing activities of households for own use', 20);
INSERT INTO sections (name, id) VALUES ('Activities of extraterritorial organisations & bodies', 21);
INSERT INTO sections (name, id) VALUES ('Utilities', 22);

-- Create a table called occupations
INSERT INTO occupations (name, id) VALUES ('Chief Executives, Senior Officials and Legislators', 1);
INSERT INTO occupations (name, id) VALUES ('Administrative and Commercial Managers', 2);
INSERT INTO occupations (name, id) VALUES ('Production and Specialised Services Managers', 3);
INSERT INTO occupations (name, id) VALUES ('Hospitality, Retail and Other Services Managers', 4);
INSERT INTO occupations (name, id) VALUES ('Information and Communications Technology Managers', 5);
INSERT INTO occupations (name, id) VALUES ('Business and Administration Professionals', 6);
INSERT INTO occupations (name, id) VALUES ('Legal, Social and Cultural Professionals', 7);
INSERT INTO occupations (name, id) VALUES ('Engineering, Science and Transport Professionals', 8);
INSERT INTO occupations (name, id) VALUES ('Health Professionals', 9);
INSERT INTO occupations (name, id) VALUES ('Teaching Professionals', 10);
INSERT INTO occupations (name, id) VALUES ('Business and Administration Associate Professionals', 11);
INSERT INTO occupations (name, id) VALUES ('Information and Communications Technology Associate Professionals', 12);
INSERT INTO occupations (name, id) VALUES ('Legal, Social, Cultural and Related Associate Professionals', 13);
INSERT INTO occupations (name, id) VALUES ('Science, Engineering and Production Technicians', 14);
INSERT INTO occupations (name, id) VALUES ('Health Associate Professionals', 15);
INSERT INTO occupations (name, id) VALUES ('Protective Services', 16);
INSERT INTO occupations (name, id) VALUES ('Sales, Marketing and Related Associate Professionals', 17);
INSERT INTO occupations (name, id) VALUES ('Information and Communications Technology Operations and User Support Technicians', 18);
INSERT INTO occupations (name, id) VALUES ('Protective Services Associate Professionals', 19);
INSERT INTO occupations (name, id) VALUES ('Personal Service Workers', 20);
INSERT INTO occupations (name, id) VALUES ('Sales Workers', 21);
INSERT INTO occupations (name, id) VALUES ('Personal Care and Related Workers', 22);
INSERT INTO occupations (name, id) VALUES ('Protective Services Workers', 23);
INSERT INTO occupations (name, id) VALUES ('Sports and Fitness Workers', 24);
INSERT INTO occupations (name, id) VALUES ('Elementary Occupations', 25);
INSERT INTO occupations (name, id) VALUES ('Armed Forces Occupations', 26);

-- Create a table called institutes
INSERT INTO institutes (name, id) VALUES ('University of Oxford', 1);
INSERT INTO institutes (name, id) VALUES ('University of Cambridge', 2);
INSERT INTO institutes (name, id) VALUES ('Imperial College London', 3);
INSERT INTO institutes (name, id) VALUES ('University College London', 4);
INSERT INTO institutes (name, id) VALUES ('London School of Economics and Political Science', 5);
INSERT INTO institutes (name, id) VALUES ('University of Edinburgh', 6);
INSERT INTO institutes (name, id) VALUES ('King''s College London', 7);
INSERT INTO institutes (name, id) VALUES ('University of Manchester', 8);
INSERT INTO institutes (name, id) VALUES ('University of Bristol', 9);
INSERT INTO institutes (name, id) VALUES ('University of Warwick', 10);
INSERT INTO institutes (name, id) VALUES ('University of Glasgow', 11);
INSERT INTO institutes (name, id) VALUES ('University of Birmingham', 12);
INSERT INTO institutes (name, id) VALUES ('University of Sheffield', 13);
INSERT INTO institutes (name, id) VALUES ('University of Southampton', 14);
INSERT INTO institutes (name, id) VALUES ('University of Leeds', 15);

-- Create a table called titles
INSERT INTO titles (name, id) VALUES ('Professor', 1);
INSERT INTO titles (name, id) VALUES ('Associate Professor', 2);
INSERT INTO titles (name, id) VALUES ('Assistant Professor', 3);
INSERT INTO titles (name, id) VALUES ('Lecturer', 4);
INSERT INTO titles (name, id) VALUES ('Senior Research Fellow', 5);
INSERT INTO titles (name, id) VALUES ('Research Fellow', 6);
INSERT INTO titles (name, id) VALUES ('Postdoctoral Researcher', 7);
INSERT INTO titles (name, id) VALUES ('PhD Student', 8);
INSERT INTO titles (name, id) VALUES ('Master Student', 9);
INSERT INTO titles (name, id) VALUES ('Bachelor Student', 10);
INSERT INTO titles (name, id) VALUES ('Research Assistant', 11);
INSERT INTO titles (name, id) VALUES ('Research Associate', 12);
INSERT INTO titles (name, id) VALUES ('Research Scientist', 13);
INSERT INTO titles (name, id) VALUES ('Research Engineer', 14);
INSERT INTO titles (name, id) VALUES ('Research Intern', 15);
INSERT INTO titles (name, id) VALUES ('Researcher', 16);
INSERT INTO titles (name, id) VALUES ('Research Manager', 17);
INSERT INTO titles (name, id) VALUES ('Research Director', 18);
INSERT INTO titles (name, id) VALUES ('Research Consultant', 19);
INSERT INTO titles (name, id) VALUES ('Research Specialist', 20);
INSERT INTO titles (name, id) VALUES ('Research Coordinator', 21);
INSERT INTO titles (name, id) VALUES ('Research Administrator', 22);
INSERT INTO titles (name, id) VALUES ('Research Officer', 23);
INSERT INTO titles (name, id) VALUES ('Research Executive', 24);



